"use strict";
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]);
const money=(v,d=0)=>Number.isFinite(Number(v))&&Number(v)>0?`${Number(v).toLocaleString("ko-KR",{maximumFractionDigits:d})}원`:"가격 확인";
function safeUrl(v){try{const u=new URL(String(v),location.href);return ["http:","https:"].includes(u.protocol)?u.href:"#"}catch{return"#"}}
function trend(i){if(i.trend==="new")return"신규";if(i.trend==="up")return`▲ ${i.rank_change||""}`;if(i.trend==="down")return`▼ ${Math.abs(i.rank_change||0)}`;return"-"}
function card(i,n){const id=encodeURIComponent(i.product_id),img=safeUrl(i.image),url=safeUrl(i.url);const image=img!=="#"?`<img loading="lazy" src="${esc(img)}" alt="${esc(i.name)}">`:"";return`<article class="card"><a class="card-img" href="product/${id}.html">${image}</a><div class="card-body"><div class="rank">${n}위 <small>${esc(trend(i))}</small></div><div class="category">${esc(i.category)}</div><h3><a href="product/${id}.html">${esc(i.name)}</a></h3><div class="price">${money(i.price)}</div><a class="primary" target="_blank" rel="nofollow sponsored noopener" href="${esc(url)}">쿠팡에서 확인</a></div></article>`}
function composite(items){const groups={};items.forEach(i=>(groups[i.category_id]??=[]).push(i));Object.values(groups).forEach(g=>g.sort((a,b)=>(a.rank||999)-(b.rank||999)));const out=[];let row=0;while(out.length<100){let added=false;for(const key of Object.keys(groups).sort()){if(groups[key][row]){out.push(groups[key][row]);added=true;if(out.length>=100)break}}if(!added)break;row++}return out}
async function loadProducts(){try{const response=await fetch("data/products.json",{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json(),items=Array.isArray(data.items)?data.items:[];if(!items.length)return;$("#emptyState").hidden=true;$("#dataStatus").textContent="상품 데이터 자동 갱신 중";$("#dataUpdated").textContent=`최근 갱신: ${String(data.updated_at||"").replace("T"," ").slice(0,16)}`;$("#rankingNote").textContent="API 카테고리별 베스트를 고르게 모아 표시합니다.";const counts={};items.forEach(i=>counts[i.category]=(counts[i.category]||0)+1);$("#categoryChips").innerHTML=Object.entries(counts).sort((a,b)=>a[0].localeCompare(b[0],"ko")).map(([name,count])=>`<a class="chip" href="category/${encodeURIComponent(name)}.html">${esc(name)} ${count}</a>`).join("");$("#productGrid").innerHTML=composite(items).map(card).join("")}catch(error){console.warn("상품 데이터를 불러오지 못했습니다.",error)}}
const units={g:{family:"weight",factor:1,basis:100,label:"100g"},kg:{family:"weight",factor:1000,basis:100,label:"100g"},ml:{family:"volume",factor:1,basis:100,label:"100ml"},L:{family:"volume",factor:1000,basis:100,label:"100ml"},"개":{family:"count",factor:1,basis:1,label:"1개"},"매":{family:"sheet",factor:1,basis:1,label:"1매"}};
const numeric=s=>Number(String($(s).value||"").replace(/,/g,"").trim());
function item(prefix){const price=numeric(`#${prefix}Price`),quantity=numeric(`#${prefix}Qty`),unit=units[$(`#${prefix}Unit`).value];return price>0&&quantity>0&&unit?{family:unit.family,label:unit.label,value:price/(quantity*unit.factor)*unit.basis}:null}
function calc(){const a=item("a"),b=item("b");$("#aResult").textContent=a?`${a.label}당 ${money(a.value,2)}`:"-";$("#bResult").textContent=b?`${b.label}당 ${money(b.value,2)}`:"-";const w=$("#calcWinner");if(!a||!b)w.textContent="가격과 용량을 입력하면 더 저렴한 쪽을 알려드립니다.";else if(a.family!==b.family)w.textContent="무게끼리(g·kg), 부피끼리(ml·L), 같은 수량 단위끼리 비교할 수 있습니다.";else if(Math.abs(a.value-b.value)<1e-6)w.textContent=`두 상품의 ${a.label}당 가격이 같습니다.`;else{const low=Math.min(a.value,b.value),high=Math.max(a.value,b.value),cheaper=a.value<b.value?"상품 A":"상품 B";w.textContent=`${cheaper}가 ${a.label}당 가격 기준 ${((high-low)/high*100).toFixed(1)}% 저렴합니다. (${money(low,2)} vs ${money(high,2)})`}}
function formatPrice(e){const digits=e.target.value.replace(/\D/g,"").replace(/^0+(?=\d)/,"");e.target.value=digits?Number(digits).toLocaleString("ko-KR"):"";calc()}
function checklist(){const boxes=[...document.querySelectorAll("[data-check]")],progress=$("#checkProgress");const update=()=>{const n=boxes.filter(b=>b.checked).length;progress.textContent=`${n} / ${boxes.length} 확인${n===boxes.length?" — 구매 준비 완료":""}`};boxes.forEach(b=>b.addEventListener("change",update));$("#resetChecklist").addEventListener("click",()=>{boxes.forEach(b=>b.checked=false);update()})}
document.querySelectorAll(".price-input").forEach(i=>i.addEventListener("input",formatPrice));["#aQty","#bQty","#aUnit","#bUnit"].forEach(s=>$(s).addEventListener("input",calc));checklist();loadProducts();
